spring:
  datasource:
    url: jdbc:h2:mem:homework
    username: sa
    password:
    driver-class-name: org.h2.Driver

  profiles:
    active: real

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        show_sql: true
 #       format_sql: true
        default_batch_fetch_size: 100
        open-in-view: false

#logging:
#  level:
#    org.hibernate.SQL: debug
#    org.hibernate.type: trace

decorator:
  datasource:
    p6spy:
      enable-logging: off